# Generated by Django 5.2.9 on 2025-12-09 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamento', '0002_plano_servico_medico_agendamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='servico',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servico',
            name='preco',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, null=True),
        ),
    ]
