# Generated by Django 6.0 on 2025-12-09 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamento', '0002_paciente'),
    ]

    operations = [
        migrations.AddField(
            model_name='medico',
            name='foto_perfil_medico',
            field=models.ImageField(blank=True, null=True, upload_to='medicos/'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='foto_perfil_paciente',
            field=models.ImageField(blank=True, null=True, upload_to='pacientes/'),
        ),
    ]
