# Generated by Django 5.2.9 on 2025-12-09 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamento', '0003_servico_descricao_servico_preco'),
    ]

    operations = [
        migrations.AddField(
            model_name='servico',
            name='planos_aceitos',
            field=models.ManyToManyField(blank=True, to='agendamento.plano'),
        ),
    ]
