# Generated by Django 6.0 on 2025-12-09 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agendamento', '0003_medico_foto_perfil_medico_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medico',
            name='foto',
        ),
    ]
