# Generated by Django 6.0 on 2025-12-10 15:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamento', '0004_remove_medico_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='plano',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='agendamento.plano'),
        ),
        migrations.AddField(
            model_name='user',
            name='plano_saude',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='agendamento.plano'),
        ),
    ]
