# Generated by Django 6.0 on 2025-12-11 17:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamento', '0005_consulta_plano_user_plano_saude'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='plano_saude',
        ),
        migrations.AddField(
            model_name='medico',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='medicos/'),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='servico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agendamento.especialidade'),
        ),
    ]
