# Generated by Django 6.0 on 2025-12-11 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamento', '0006_remove_user_plano_saude_medico_foto_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medico',
            name='foto',
        ),
        migrations.AddField(
            model_name='user',
            name='plano_saude',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='agendamento.plano'),
        ),
    ]
